# Generated by Django 3.1.7 on 2022-07-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kanshoku',
            field=models.IntegerField(blank=True, null=True, verbose_name='感触'),
        ),
    ]
