# Generated by Django 3.1.7 on 2022-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0002_customer_kanshoku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kanshoku',
            field=models.IntegerField(default=0, verbose_name='感触'),
        ),
    ]
