# Generated by Django 3.1.7 on 2022-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0004_auto_20220722_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dm_check',
            field=models.BooleanField(default=False, verbose_name='DMリスト'),
        ),
    ]
