# Generated by Django 3.1.7 on 2022-08-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0005_customer_dm_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dm_check',
            field=models.BooleanField(default=False, null=True, verbose_name='DMリスト'),
        ),
    ]
