# Generated by Django 3.1.7 on 2022-10-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0007_auto_20220804_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nohin_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='納品'),
        ),
    ]
