# Generated by Django 3.1.7 on 2022-10-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0009_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='sell_cus_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='顧客ID'),
        ),
    ]
