# Generated by Django 3.1.7 on 2022-11-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0010_auto_20221026_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='nohin_day',
            new_name='nouhin_day',
        ),
    ]
