# Generated by Django 3.1.7 on 2022-11-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0012_auto_20221127_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dm_day',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='DM'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gaisho_day',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='外商'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel_day',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='TEL'),
        ),
    ]
