# Generated by Django 4.2.1 on 2025-01-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0016_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
